/// Catálogo local com marca, modelo, tanque e média (gasolina e álcool).
///
/// Valores de uso misto (cidade e estrada), fora de bancada.
/// O piloto ajusta depois da própria média. Sem FIPE e sem placa.
/// Onde a moto roda. Filtra a lista e escolhe a foto de partida.
///
/// cidade: urbana, street pequena, scooter e trabalho.
/// trail: trail, big trail e adventure.
/// estrada: custom, clássica e touring de asfalto.
/// esporte: carenada e naked de alta performance.
enum UsoCatalogo { cidade, trail, estrada, esporte }

class ModeloCatalogo {
  const ModeloCatalogo({
    required this.marca,
    required this.modelo,
    required this.cilindradaCc,
    required this.kmPorLitro,
    required this.tanqueLitros,
    required this.uso,
    this.kmPorLitroAlcool,
    this.flex = true,
    this.dica = '',
    this.nomeLista,
    this.psiDianteiro = 25,
    this.psiTraseiro = 29,
    this.oleoKm = 4000,
    this.correnteKm,
  });

  final String marca;
  final String modelo;
  final int cilindradaCc;

  /// Gasolina, uso misto.
  final double kmPorLitro;

  /// Álcool. Null = moto apenas a gasolina.
  final double? kmPorLitroAlcool;

  final double tanqueLitros;
  final bool flex;
  final String dica;
  final UsoCatalogo uso;

  /// Texto da lista, se o modelo precisar de apelido (Fan, Titan…).
  final String? nomeLista;

  final int psiDianteiro;
  final int psiTraseiro;
  final int oleoKm;

  /// Null = scooter / CVT / cardã, sem corrente.
  final int? correnteKm;

  String get rotulo => nomeLista ?? '$marca $modelo';

  /// Foto da categoria. Sem foto de fabricante.
  String get assetSilhueta {
    switch (uso) {
      case UsoCatalogo.esporte:
        return 'assets/catalogo/esporte.png';
      case UsoCatalogo.trail:
        return 'assets/catalogo/trail.png';
      case UsoCatalogo.estrada:
        return 'assets/catalogo/estrada.png';
      case UsoCatalogo.cidade:
        return 'assets/catalogo/cidade.png';
    }
  }
}

List<ModeloCatalogo> catalogoFiltrado(UsoCatalogo? uso) {
  if (uso == null) return catalogoMotos;
  return [
    for (final m in catalogoMotos)
      if (m.uso == uso) m,
  ];
}

const List<ModeloCatalogo> catalogoMotos = [
  // Cidade: urbana, street pequena, scooter e trabalho.
  ModeloCatalogo(
    marca: 'Mottu',
    modelo: 'Sport 110i',
    cilindradaCc: 109,
    kmPorLitro: 45,
    tanqueLitros: 10,
    flex: false,
    uso: UsoCatalogo.cidade,
    dica: 'Motor de 109 cc pensado para entrega, com tanque de 10 litros que dá autonomia longa para o tamanho da moto.',
    psiTraseiro: 32,
    correnteKm: 1000,
  ),
  ModeloCatalogo(
    marca: 'Honda',
    modelo: 'Biz 110i',
    cilindradaCc: 109,
    kmPorLitro: 46,
    tanqueLitros: 5.1,
    flex: false,
    uso: UsoCatalogo.cidade,
    dica: 'Só roda com gasolina, e o tanque de 5,1 litros pede abastecimento mais frequente que o da Biz 125.',
    psiTraseiro: 28,
    oleoKm: 6000,
    correnteKm: 1000,
  ),
  ModeloCatalogo(
    marca: 'Honda',
    modelo: 'Pop 110i',
    cilindradaCc: 110,
    kmPorLitro: 49,
    tanqueLitros: 4.2,
    flex: false,
    uso: UsoCatalogo.cidade,
    dica: 'Apenas gasolina. Tanque 4,2 L, enche mais vezes e rende bem no litro. Corrente cerca de 1.000 km.',
    psiDianteiro: 25,
    psiTraseiro: 32,
    correnteKm: 1000,
  ),
  ModeloCatalogo(
    marca: 'Yamaha',
    modelo: 'Crypton 115',
    cilindradaCc: 114,
    kmPorLitro: 38,
    tanqueLitros: 4.2,
    flex: false,
    uso: UsoCatalogo.cidade,
    dica: 'Produzida até 2016, hoje só aparece usada, sempre a gasolina e com tanque pequeno de 4,2 litros.',
    psiTraseiro: 28,
    oleoKm: 3000,
    correnteKm: 1000,
  ),
  ModeloCatalogo(
    marca: 'Honda',
    modelo: 'Biz 125',
    cilindradaCc: 124,
    kmPorLitro: 48,
    kmPorLitroAlcool: 37,
    tanqueLitros: 5,
    uso: UsoCatalogo.cidade,
    dica: 'FlexOne, semiautomática. Tanque 5 L. No álcool a média cai ~25%. Corrente ~1.000 km.',
    psiDianteiro: 25,
    psiTraseiro: 32,
    correnteKm: 1000,
  ),
  ModeloCatalogo(
    marca: 'Honda',
    modelo: 'Elite 125',
    cilindradaCc: 124,
    kmPorLitro: 42,
    tanqueLitros: 5.3,
    flex: false,
    uso: UsoCatalogo.cidade,
    dica: 'Scooter apenas a gasolina. Tanque 5,3 L. Idling Stop desliga o motor no farol.',
    psiDianteiro: 25,
    psiTraseiro: 32,
  ),
  ModeloCatalogo(
    marca: 'Shineray',
    modelo: 'Jet 125',
    cilindradaCc: 124,
    kmPorLitro: 38,
    tanqueLitros: 3,
    flex: false,
    uso: UsoCatalogo.cidade,
    dica: 'Tanque de 3 litros, o menor da lista, pede parada no posto quase todo dia de uso. O manual manda trocar o óleo a cada 1.000 km, bem mais cedo que nas japonesas.',
    psiDianteiro: 26,
    psiTraseiro: 28,
    oleoKm: 1000,
    correnteKm: 1000,
  ),
  ModeloCatalogo(
    marca: 'Shineray',
    modelo: 'Worker 125',
    cilindradaCc: 124,
    kmPorLitro: 38,
    tanqueLitros: 14,
    flex: false,
    uso: UsoCatalogo.cidade,
    dica: 'O tanque de 14 litros é grande para a categoria e ajuda quem roda o dia inteiro trabalhando, sempre com gasolina.',
    psiDianteiro: 28,
    psiTraseiro: 32,
    correnteKm: 1000,
  ),
  ModeloCatalogo(
    marca: 'Yamaha',
    modelo: 'ZR Hybrid',
    cilindradaCc: 125,
    kmPorLitro: 48,
    tanqueLitros: 5.2,
    flex: false,
    uso: UsoCatalogo.cidade,
    dica: 'Scooter híbrida, apenas gasolina. Tanque 5,2 L. Stop & Start ajuda no farol.',
    psiDianteiro: 25,
    psiTraseiro: 32,
  ),
  ModeloCatalogo(
    marca: 'Avelloz',
    modelo: 'AZ125 Alfa',
    cilindradaCc: 125,
    kmPorLitro: 40,
    tanqueLitros: 5,
    flex: false,
    uso: UsoCatalogo.cidade,
    dica: 'Motor de 125 cc com injeção eletrônica e tanque de 5 litros, pensada para trajeto curto na cidade.',
    correnteKm: 1000,
  ),
  ModeloCatalogo(
    marca: 'Yamaha',
    modelo: 'Neo 125',
    cilindradaCc: 125,
    kmPorLitro: 40,
    tanqueLitros: 4.2,
    flex: false,
    uso: UsoCatalogo.cidade,
    dica: 'Scooter automática sem embreagem manual, tanque pequeno de 4,2 litros pede reabastecimento frequente.',
    psiTraseiro: 28,
    oleoKm: 3000,
  ),
  ModeloCatalogo(
    marca: 'Yamaha',
    modelo: 'Factor 150',
    cilindradaCc: 149,
    kmPorLitro: 42,
    kmPorLitroAlcool: 32,
    tanqueLitros: 15.4,
    uso: UsoCatalogo.cidade,
    dica:
        'BlueFlex. Tanque 15,4 L, poucas paradas no posto. Corrente ~1.000 km.',
    correnteKm: 1000,
  ),
  ModeloCatalogo(
    marca: 'Yamaha',
    modelo: 'FZ15',
    cilindradaCc: 149,
    kmPorLitro: 40,
    kmPorLitroAlcool: 30,
    tanqueLitros: 11.9,
    uso: UsoCatalogo.cidade,
    dica: 'BlueFlex, street. Tanque 11,9 L. ABS na dianteira nas versões novas. Corrente ~1.000 km.',
    correnteKm: 1000,
  ),
  ModeloCatalogo(
    marca: 'Haojue',
    modelo: 'DK 150',
    cilindradaCc: 149,
    kmPorLitro: 36,
    tanqueLitros: 12.5,
    flex: false,
    uso: UsoCatalogo.cidade,
    dica: 'Street de trabalho com tanque de 12,5 litros e boa fama de economia no uso urbano.',
    psiDianteiro: 28,
    psiTraseiro: 32,
    oleoKm: 3000,
    correnteKm: 1000,
  ),
  ModeloCatalogo(
    marca: 'Yamaha',
    modelo: 'Fazer 150',
    cilindradaCc: 150,
    kmPorLitro: 40,
    kmPorLitroAlcool: 30,
    tanqueLitros: 15.2,
    uso: UsoCatalogo.cidade,
    dica: 'BlueFlex, street. Tanque 15,2 L. No álcool a média cai. Corrente ~1.000 km.',
    correnteKm: 1000,
  ),
  ModeloCatalogo(
    marca: 'Yamaha',
    modelo: 'NMax 160',
    cilindradaCc: 155,
    kmPorLitro: 38,
    tanqueLitros: 7.1,
    flex: false,
    uso: UsoCatalogo.cidade,
    dica: 'Scooter apenas gasolina. Tanque 7,1 L, autonomia menor que o PCX.',
    psiDianteiro: 25,
    psiTraseiro: 32,
  ),
  ModeloCatalogo(
    marca: 'Yamaha',
    modelo: 'Aerox 160',
    cilindradaCc: 155,
    kmPorLitro: 35,
    tanqueLitros: 5.5,
    flex: false,
    uso: UsoCatalogo.cidade,
    dica: 'Scooter esportiva com tanque de 5,5 litros, autonomia curta perto de 190 km. O motor de 155 cc é o mesmo da NMax.',
    psiDianteiro: 29,
    oleoKm: 3000,
  ),
  ModeloCatalogo(
    marca: 'Honda',
    modelo: 'PCX 160',
    cilindradaCc: 157,
    kmPorLitro: 40,
    tanqueLitros: 8.1,
    flex: false,
    uso: UsoCatalogo.cidade,
    dica: 'Scooter apenas a gasolina. Tanque 8,1 L. Sem álcool no tanque.',
    psiDianteiro: 25,
    psiTraseiro: 32,
  ),
  ModeloCatalogo(
    marca: 'Honda',
    modelo: 'ADV 160',
    cilindradaCc: 157,
    kmPorLitro: 38,
    tanqueLitros: 8.1,
    flex: false,
    uso: UsoCatalogo.cidade,
    dica: 'Scooter aventureira, apenas gasolina. Mesmo tanque do PCX (8,1 L).',
    psiDianteiro: 25,
    psiTraseiro: 32,
  ),
  ModeloCatalogo(
    marca: 'Bajaj',
    modelo: 'Dominar NS160',
    cilindradaCc: 160,
    kmPorLitro: 38,
    tanqueLitros: 12,
    flex: false,
    uso: UsoCatalogo.cidade,
    dica:
        'Consumo baixo e moto leve, boa entrada para uso urbano só a gasolina.',
    psiTraseiro: 28,
    oleoKm: 5000,
    correnteKm: 500,
  ),
  ModeloCatalogo(
    marca: 'Honda',
    modelo: 'CG 160',
    cilindradaCc: 163,
    kmPorLitro: 41,
    kmPorLitroAlcool: 35,
    tanqueLitros: 16.1,
    uso: UsoCatalogo.cidade,
    nomeLista: 'Honda CG 160 (Fan / Titan / Start)',
    dica: 'Flex (Fan, Titan ou Start). Tanque 16,1 L, autonomia longa. Óleo ~4.000 km. Corrente ~1.000 km. Pneu 25/29 PSI.',
    correnteKm: 1000,
  ),
  ModeloCatalogo(
    marca: 'Dafra',
    modelo: 'NH 190',
    cilindradaCc: 183,
    kmPorLitro: 32,
    tanqueLitros: 11,
    flex: false,
    uso: UsoCatalogo.cidade,
    dica: 'Voltada para quem usa a moto como ferramenta de trabalho, vem com freios combinados de série.',
    psiDianteiro: 29,
    psiTraseiro: 33,
    oleoKm: 3000,
    correnteKm: 1000,
  ),
  ModeloCatalogo(
    marca: 'Bajaj',
    modelo: 'Dominar NS200',
    cilindradaCc: 200,
    kmPorLitro: 28,
    tanqueLitros: 12,
    flex: false,
    uso: UsoCatalogo.cidade,
    dica: 'Naked urbana só a gasolina, sem para-brisa, feita mais para cidade e trecho curto.',
    psiTraseiro: 28,
    oleoKm: 5000,
    correnteKm: 500,
  ),
  ModeloCatalogo(
    marca: 'KTM',
    modelo: 'Duke 200',
    cilindradaCc: 200,
    kmPorLitro: 26,
    tanqueLitros: 13.7,
    flex: false,
    uso: UsoCatalogo.cidade,
    dica: 'Naked leve para uso urbano, tanque de 13,7 litros dá autonomia razoável no dia a dia.',
    psiDianteiro: 32,
    psiTraseiro: 36,
    oleoKm: 7500,
    correnteKm: 1000,
  ),
  ModeloCatalogo(
    marca: 'Yamaha',
    modelo: 'Fazer 250',
    cilindradaCc: 249,
    kmPorLitro: 32,
    tanqueLitros: 14.2,
    flex: false,
    uso: UsoCatalogo.cidade,
    nomeLista: 'Yamaha Fazer 250 / FZ25',
    dica: 'Apenas gasolina. Tanque 14,2 L. Sem álcool. Corrente ~1.000 km.',
    correnteKm: 1000,
  ),
  ModeloCatalogo(
    marca: 'Yamaha',
    modelo: 'XMAX 250',
    cilindradaCc: 249,
    kmPorLitro: 28,
    tanqueLitros: 13.2,
    flex: false,
    uso: UsoCatalogo.cidade,
    dica: 'Scooter grande com porta-capacete e espaço para bagagem, aguenta trecho de estrada apesar do jeito urbano.',
    psiDianteiro: 29,
    oleoKm: 6000,
  ),
  ModeloCatalogo(
    marca: 'Dafra',
    modelo: 'Citycom 300',
    cilindradaCc: 278,
    kmPorLitro: 27,
    tanqueLitros: 10,
    flex: false,
    uso: UsoCatalogo.cidade,
    dica: 'Scooter automática com transmissão por correia, sem corrente para lubrificar de tempos em tempos.',
    psiDianteiro: 29,
    psiTraseiro: 33,
    oleoKm: 5000,
  ),
  ModeloCatalogo(
    marca: 'Honda',
    modelo: 'CB 300F Twister',
    cilindradaCc: 294,
    kmPorLitro: 29,
    kmPorLitroAlcool: 22,
    tanqueLitros: 14.1,
    uso: UsoCatalogo.cidade,
    dica: 'Flex. Cidade e viagem curta. No álcool a média cai. Corrente ~1.000 km.',
    correnteKm: 1000,
  ),
  ModeloCatalogo(
    marca: 'BMW',
    modelo: 'G 310 R',
    cilindradaCc: 313,
    kmPorLitro: 28,
    tanqueLitros: 11,
    flex: false,
    uso: UsoCatalogo.cidade,
    dica: 'Moto só a gasolina, com tanque de 11 litros que pede abastecimento mais frequente na cidade.',
    psiDianteiro: 33,
    psiTraseiro: 36,
    oleoKm: 10000,
    correnteKm: 1000,
  ),
  ModeloCatalogo(
    marca: 'Triumph',
    modelo: 'Speed 400',
    cilindradaCc: 398,
    kmPorLitro: 28,
    tanqueLitros: 13,
    flex: false,
    uso: UsoCatalogo.cidade,
    dica: 'Naked apenas gasolina. Tanque 13 L. Cidade e trecho curto. Corrente ~1.000 km.',
    oleoKm: 6000,
    correnteKm: 1000,
  ),
  ModeloCatalogo(
    marca: 'Suzuki',
    modelo: 'Burgman 400',
    cilindradaCc: 400,
    kmPorLitro: 22,
    tanqueLitros: 13.5,
    flex: false,
    uso: UsoCatalogo.cidade,
    dica: 'Scooter grande de transmissão automática, sem corrente porque a tração é por correia.',
    psiDianteiro: 29,
    psiTraseiro: 33,
    oleoKm: 6000,
  ),
  ModeloCatalogo(
    marca: 'Royal Enfield',
    modelo: 'Guerrilla 450',
    cilindradaCc: 452,
    kmPorLitro: 27,
    tanqueLitros: 11,
    flex: false,
    uso: UsoCatalogo.cidade,
    dica: 'Roadster pensada para o dia a dia, tanque de 11 litros é pequeno para viagem sem reabastecer.',
    psiDianteiro: 29,
    psiTraseiro: 33,
    oleoKm: 6000,
    correnteKm: 500,
  ),

  // Trail: trail, big trail e adventure.
  ModeloCatalogo(
    marca: 'Yamaha',
    modelo: 'Crosser 150',
    cilindradaCc: 149,
    kmPorLitro: 38,
    kmPorLitroAlcool: 30,
    tanqueLitros: 12,
    uso: UsoCatalogo.trail,
    dica:
        'BlueFlex, trail. Tanque 12 L. No álcool a média cai. Pneu 22/29 PSI.',
    psiDianteiro: 22,
    correnteKm: 1000,
  ),
  ModeloCatalogo(
    marca: 'Haojue',
    modelo: 'NK 150',
    cilindradaCc: 149,
    kmPorLitro: 37,
    tanqueLitros: 12.2,
    flex: false,
    uso: UsoCatalogo.trail,
    dica: 'A versão brasileira vem com injeção eletrônica e tanque de 12,2 litros, boa autonomia para uma trail leve.',
    oleoKm: 3000,
    correnteKm: 1000,
  ),
  ModeloCatalogo(
    marca: 'Honda',
    modelo: 'NXR 160 Bros',
    cilindradaCc: 163,
    kmPorLitro: 35,
    kmPorLitroAlcool: 28,
    tanqueLitros: 12,
    uso: UsoCatalogo.trail,
    dica: 'Flex, trail. Tanque interno 12 L. No álcool a média cai. Pneu 22/29 PSI. Corrente ~1.000 km.',
    psiDianteiro: 22,
    correnteKm: 1000,
  ),
  ModeloCatalogo(
    marca: 'Shineray',
    modelo: 'SHI 175',
    cilindradaCc: 175,
    kmPorLitro: 32,
    tanqueLitros: 14.5,
    flex: false,
    uso: UsoCatalogo.trail,
    dica: 'Trail de entrada com tanque de 14,5 litros, que rende bem na cidade e cai um pouco em velocidade de estrada.',
    psiDianteiro: 22,
    psiTraseiro: 28,
    oleoKm: 1000,
    correnteKm: 1000,
  ),
  ModeloCatalogo(
    marca: 'Honda',
    modelo: 'XRE 190',
    cilindradaCc: 184,
    kmPorLitro: 36,
    kmPorLitroAlcool: 28,
    tanqueLitros: 12,
    uso: UsoCatalogo.trail,
    dica: 'Flex, trail leve. Mesmo tanque da Bros, um pouco mais de fôlego. Pneu 22/29 PSI.',
    psiDianteiro: 22,
    correnteKm: 1000,
  ),
  ModeloCatalogo(
    marca: 'Yamaha',
    modelo: 'Ténéré 250',
    cilindradaCc: 249,
    kmPorLitro: 28,
    tanqueLitros: 16,
    flex: false,
    uso: UsoCatalogo.trail,
    nomeLista: 'Yamaha XTZ 250 Ténéré',
    dica: 'Trail clássica, apenas gasolina. Tanque 16 L. Pneu 22/29 PSI. Corrente ~1.000 km.',
    psiDianteiro: 22,
    correnteKm: 1000,
  ),
  ModeloCatalogo(
    marca: 'Yamaha',
    modelo: 'Lander 250',
    cilindradaCc: 249,
    kmPorLitro: 32,
    tanqueLitros: 13.6,
    flex: false,
    uso: UsoCatalogo.trail,
    dica: 'Trail apenas a gasolina. Tanque 13,6 L. Relação e pneu traseiro gastam cedo na terra. Pneu 22/29 PSI.',
    psiDianteiro: 22,
    correnteKm: 1000,
  ),
  ModeloCatalogo(
    marca: 'Shineray',
    modelo: 'SHI 250',
    cilindradaCc: 250,
    kmPorLitro: 31,
    tanqueLitros: 18,
    flex: false,
    uso: UsoCatalogo.trail,
    dica: 'Tanque de 18 litros e freios combinados marcam essa trail, sempre abastecida com gasolina.',
    psiDianteiro: 26,
    oleoKm: 3000,
    correnteKm: 1000,
  ),
  ModeloCatalogo(
    marca: 'Honda',
    modelo: 'XRE 300',
    cilindradaCc: 292,
    kmPorLitro: 26,
    kmPorLitroAlcool: 20,
    tanqueLitros: 14,
    uso: UsoCatalogo.trail,
    dica: 'Flex, trail. Tanque 14 L. Óleo e relação pedem atenção no uso de terra. Pneu 22/29 PSI.',
    psiDianteiro: 22,
    correnteKm: 1000,
  ),
  ModeloCatalogo(
    marca: 'Honda',
    modelo: 'Sahara 300',
    cilindradaCc: 294,
    kmPorLitro: 30,
    kmPorLitroAlcool: 24,
    tanqueLitros: 13.8,
    uso: UsoCatalogo.trail,
    dica: 'Flex, sucessor da XRE 300. Tanque 13,8 L, cerca de 400 km na gasolina. Pneu 22/29 PSI.',
    psiDianteiro: 22,
    correnteKm: 1000,
  ),
  ModeloCatalogo(
    marca: 'Honda',
    modelo: 'Tornado 300',
    cilindradaCc: 294,
    kmPorLitro: 29,
    kmPorLitroAlcool: 23,
    tanqueLitros: 13.8,
    uso: UsoCatalogo.trail,
    nomeLista: 'Honda XR 300 Tornado',
    dica: 'Flex, irmã da Sahara com foco em terra. Mesmo tanque 13,8 L e motor 300. Pneu 22/29 PSI.',
    psiDianteiro: 22,
    correnteKm: 1000,
  ),
  ModeloCatalogo(
    marca: 'Kawasaki',
    modelo: 'Versys-X 300',
    cilindradaCc: 296,
    kmPorLitro: 22,
    tanqueLitros: 17,
    flex: false,
    uso: UsoCatalogo.trail,
    dica: 'Trail leve, apenas gasolina. Tanque 17 L. Pneu 22/29 PSI. Óleo ~6.000 km.',
    psiDianteiro: 22,
    oleoKm: 6000,
    correnteKm: 1000,
  ),
  ModeloCatalogo(
    marca: 'BMW',
    modelo: 'G 310 GS',
    cilindradaCc: 313,
    kmPorLitro: 26,
    tanqueLitros: 11,
    flex: false,
    uso: UsoCatalogo.trail,
    dica: 'Entrada da família GS, apenas gasolina. Tanque 11 L. Corrente ~1.000 km. Óleo ~6.000 km.',
    psiDianteiro: 33,
    psiTraseiro: 36,
    oleoKm: 6000,
    correnteKm: 1000,
  ),
  ModeloCatalogo(
    marca: 'Royal Enfield',
    modelo: 'Hunter 350',
    cilindradaCc: 349,
    kmPorLitro: 32,
    tanqueLitros: 13,
    flex: false,
    uso: UsoCatalogo.trail,
    dica: 'Apenas gasolina. Tanque 13 L. Entrada da Royal. Óleo ~6.000 km.',
    psiDianteiro: 25,
    psiTraseiro: 32,
    oleoKm: 6000,
    correnteKm: 1000,
  ),
  ModeloCatalogo(
    marca: 'Royal Enfield',
    modelo: 'Classic 350',
    cilindradaCc: 349,
    kmPorLitro: 30,
    tanqueLitros: 13,
    flex: false,
    uso: UsoCatalogo.trail,
    dica: 'Custom, apenas gasolina. Tanque 13 L. Viagem curta e média. Óleo ~6.000 km.',
    psiDianteiro: 25,
    psiTraseiro: 32,
    oleoKm: 6000,
    correnteKm: 1000,
  ),
  ModeloCatalogo(
    marca: 'Royal Enfield',
    modelo: 'Meteor 350',
    cilindradaCc: 349,
    kmPorLitro: 30,
    tanqueLitros: 15,
    flex: false,
    uso: UsoCatalogo.trail,
    dica: 'Custom, apenas gasolina. Tanque 15 L, mais autonomia que a Classic. Óleo ~6.000 km.',
    psiDianteiro: 25,
    psiTraseiro: 32,
    oleoKm: 6000,
    correnteKm: 1000,
  ),
  ModeloCatalogo(
    marca: 'Bajaj',
    modelo: 'Dominar 400',
    cilindradaCc: 373,
    kmPorLitro: 28,
    tanqueLitros: 13,
    flex: false,
    uso: UsoCatalogo.trail,
    dica: 'Moto só a gasolina, com para-brisa e tanque de 13 litros pensados para estrada.',
    psiDianteiro: 29,
    psiTraseiro: 32,
    oleoKm: 5000,
    correnteKm: 500,
  ),
  ModeloCatalogo(
    marca: 'Triumph',
    modelo: 'Scrambler 400 X',
    cilindradaCc: 398,
    kmPorLitro: 26,
    tanqueLitros: 13,
    flex: false,
    uso: UsoCatalogo.trail,
    dica: 'Scrambler, apenas gasolina. Tanque 13 L. Trecho de terra leve. Óleo ~6.000 km.',
    psiDianteiro: 22,
    oleoKm: 6000,
    correnteKm: 1000,
  ),
  ModeloCatalogo(
    marca: 'CFMOTO',
    modelo: 'Ibex 450',
    cilindradaCc: 450,
    kmPorLitro: 24,
    tanqueLitros: 17.5,
    flex: false,
    uso: UsoCatalogo.trail,
    dica: 'Trail, apenas gasolina. Tanque 17,5 L. Pneu 22/29 PSI. Óleo ~6.000 km.',
    psiDianteiro: 22,
    oleoKm: 6000,
    correnteKm: 1000,
  ),
  ModeloCatalogo(
    marca: 'Royal Enfield',
    modelo: 'Himalayan 450',
    cilindradaCc: 452,
    kmPorLitro: 26,
    tanqueLitros: 17,
    flex: false,
    uso: UsoCatalogo.trail,
    dica: 'Trail, apenas gasolina. Tanque 17 L. Uso misto. Pneu 22/29 PSI. Óleo ~6.000 km.',
    psiDianteiro: 22,
    oleoKm: 6000,
    correnteKm: 1000,
  ),
  ModeloCatalogo(
    marca: 'Honda',
    modelo: 'CB 500X',
    cilindradaCc: 471,
    kmPorLitro: 25,
    tanqueLitros: 17.5,
    flex: false,
    uso: UsoCatalogo.trail,
    nomeLista: 'Honda CB 500X / NX 500',
    dica: 'Trail média, apenas gasolina. Tanque 17,5 L. Óleo ~6.000 km. Pneu 22/29 PSI.',
    psiDianteiro: 22,
    oleoKm: 6000,
    correnteKm: 1000,
  ),
  ModeloCatalogo(
    marca: 'Suzuki',
    modelo: 'V-Strom 650',
    cilindradaCc: 645,
    kmPorLitro: 20,
    tanqueLitros: 20,
    flex: false,
    uso: UsoCatalogo.trail,
    dica: 'Big trail, apenas gasolina. Tanque 20 L. Uso misto. Óleo ~6.000 km.',
    psiDianteiro: 29,
    psiTraseiro: 36,
    oleoKm: 6000,
    correnteKm: 1000,
  ),
  ModeloCatalogo(
    marca: 'Kawasaki',
    modelo: 'Versys 650',
    cilindradaCc: 649,
    kmPorLitro: 18,
    tanqueLitros: 21,
    flex: false,
    uso: UsoCatalogo.trail,
    dica: 'Touring, apenas gasolina. Tanque 21 L. Óleo ~6.000 km. Corrente ~1.000 km.',
    psiDianteiro: 29,
    psiTraseiro: 36,
    oleoKm: 6000,
    correnteKm: 1000,
  ),
  ModeloCatalogo(
    marca: 'Triumph',
    modelo: 'Tiger Sport 660',
    cilindradaCc: 660,
    kmPorLitro: 19,
    tanqueLitros: 17.2,
    flex: false,
    uso: UsoCatalogo.trail,
    dica: 'Sport touring de entrada com tanque de 17,2 litros bom para estrada, com consumo mais alto na cidade.',
    psiDianteiro: 33,
    psiTraseiro: 36,
    oleoKm: 16000,
    correnteKm: 1000,
  ),
  ModeloCatalogo(
    marca: 'Yamaha',
    modelo: 'Ténéré 700',
    cilindradaCc: 689,
    kmPorLitro: 20,
    tanqueLitros: 16,
    flex: false,
    uso: UsoCatalogo.trail,
    dica: 'Big trail, apenas gasolina. Tanque 16 L. Pneu 22/29 PSI. Óleo ~6.000 km.',
    psiDianteiro: 22,
    oleoKm: 6000,
    correnteKm: 1000,
  ),
  ModeloCatalogo(
    marca: 'CFMOTO',
    modelo: 'Ibex 700',
    cilindradaCc: 693,
    kmPorLitro: 20,
    tanqueLitros: 20,
    flex: false,
    uso: UsoCatalogo.trail,
    dica: 'Crossover, apenas gasolina. Tanque 20 L. Óleo ~6.000 km. Corrente ~1.000 km.',
    psiDianteiro: 29,
    psiTraseiro: 36,
    oleoKm: 6000,
    correnteKm: 1000,
  ),
  ModeloCatalogo(
    marca: 'Honda',
    modelo: 'NC 750X',
    cilindradaCc: 745,
    kmPorLitro: 26,
    tanqueLitros: 14.1,
    flex: false,
    uso: UsoCatalogo.trail,
    dica: 'Crossover, apenas gasolina. Tanque 14,1 L, o resto é porta-capacete. Óleo ~6.000 km.',
    psiDianteiro: 29,
    psiTraseiro: 36,
    oleoKm: 6000,
    correnteKm: 1000,
  ),
  ModeloCatalogo(
    marca: 'Honda',
    modelo: 'XL 750 Transalp',
    cilindradaCc: 755,
    kmPorLitro: 22,
    tanqueLitros: 16.9,
    flex: false,
    uso: UsoCatalogo.trail,
    dica: 'Trail de viagem, apenas gasolina. Tanque 16,9 L. Pneu 22/29 PSI. Óleo ~6.000 km.',
    psiDianteiro: 22,
    oleoKm: 6000,
    correnteKm: 1000,
  ),
  ModeloCatalogo(
    marca: 'Suzuki',
    modelo: 'V-Strom 800DE',
    cilindradaCc: 776,
    kmPorLitro: 19,
    tanqueLitros: 20,
    flex: false,
    uso: UsoCatalogo.trail,
    dica: 'Big trail, apenas gasolina. Tanque 20 L. Aro 21 na dianteira. Óleo ~6.000 km.',
    psiDianteiro: 22,
    oleoKm: 6000,
    correnteKm: 1000,
  ),
  ModeloCatalogo(
    marca: 'BMW',
    modelo: 'F 750 GS',
    cilindradaCc: 853,
    kmPorLitro: 20,
    tanqueLitros: 15,
    flex: false,
    uso: UsoCatalogo.trail,
    dica: 'Trail média, apenas gasolina. Tanque 15 L. Mesmo motor da F 850, mais manso. Corrente ~1.000 km.',
    psiDianteiro: 36,
    psiTraseiro: 42,
    oleoKm: 10000,
    correnteKm: 1000,
  ),
  ModeloCatalogo(
    marca: 'BMW',
    modelo: 'F 850 GS',
    cilindradaCc: 853,
    kmPorLitro: 18,
    tanqueLitros: 15,
    flex: false,
    uso: UsoCatalogo.trail,
    dica: 'Trail média, apenas gasolina. Tanque 15 L. Corrente ~1.000 km. Óleo ~10.000 km.',
    psiDianteiro: 36,
    psiTraseiro: 42,
    oleoKm: 10000,
    correnteKm: 1000,
  ),
  ModeloCatalogo(
    marca: 'BMW',
    modelo: 'F 850 GS Adventure',
    cilindradaCc: 853,
    kmPorLitro: 18,
    tanqueLitros: 23,
    flex: false,
    uso: UsoCatalogo.trail,
    dica: 'Irmã da F 850 com tanque 23 L. Apenas gasolina. Corrente ~1.000 km. Óleo ~10.000 km.',
    psiDianteiro: 36,
    psiTraseiro: 42,
    oleoKm: 10000,
    correnteKm: 1000,
  ),
  ModeloCatalogo(
    marca: 'Triumph',
    modelo: 'Tiger 900',
    cilindradaCc: 888,
    kmPorLitro: 18,
    tanqueLitros: 20,
    flex: false,
    uso: UsoCatalogo.trail,
    dica: 'Big trail, apenas gasolina. Tanque 20 L. Viagem longa. Óleo ~6.000 km.',
    psiDianteiro: 22,
    oleoKm: 6000,
    correnteKm: 1000,
  ),
  ModeloCatalogo(
    marca: 'KTM',
    modelo: '890 R',
    cilindradaCc: 889,
    kmPorLitro: 21,
    tanqueLitros: 20,
    flex: false,
    uso: UsoCatalogo.trail,
    dica: 'Big trail com tanque de 20 litros pensado para trecho longo fora do asfalto.',
    psiDianteiro: 33,
    psiTraseiro: 36,
    oleoKm: 15000,
    correnteKm: 1000,
  ),
  ModeloCatalogo(
    marca: 'BMW',
    modelo: 'F 900 GS',
    cilindradaCc: 895,
    kmPorLitro: 18,
    tanqueLitros: 14.5,
    flex: false,
    uso: UsoCatalogo.trail,
    dica: 'Sucessora da F 850, apenas gasolina. Tanque 14,5 L. Corrente ~1.000 km.',
    psiDianteiro: 36,
    psiTraseiro: 42,
    oleoKm: 10000,
    correnteKm: 1000,
  ),
  ModeloCatalogo(
    marca: 'Suzuki',
    modelo: 'V-Strom 1050',
    cilindradaCc: 1037,
    kmPorLitro: 20,
    tanqueLitros: 20,
    flex: false,
    uso: UsoCatalogo.trail,
    dica: 'Big trail de viagem, o tanque de 20 litros permite rodar mais de 400 km entre paradas.',
    oleoKm: 6000,
    correnteKm: 1000,
  ),
  ModeloCatalogo(
    marca: 'Kawasaki',
    modelo: 'Versys 1000',
    cilindradaCc: 1043,
    kmPorLitro: 15,
    tanqueLitros: 21,
    flex: false,
    uso: UsoCatalogo.trail,
    dica: 'Tanque de 21 litros dá boa autonomia para viagem longa.',
    psiDianteiro: 36,
    psiTraseiro: 36,
    oleoKm: 6000,
    correnteKm: 1000,
  ),
  ModeloCatalogo(
    marca: 'Honda',
    modelo: 'CRF 1100 Africa Twin',
    cilindradaCc: 1084,
    kmPorLitro: 18,
    tanqueLitros: 18.8,
    flex: false,
    uso: UsoCatalogo.trail,
    dica: 'Big trail, apenas gasolina. Tanque 18,8 L. Viagem longa. Óleo ~6.000 km.',
    psiDianteiro: 22,
    oleoKm: 6000,
    correnteKm: 1000,
  ),
  ModeloCatalogo(
    marca: 'Ducati',
    modelo: 'Multistrada V4',
    cilindradaCc: 1158,
    kmPorLitro: 15,
    tanqueLitros: 22,
    flex: false,
    uso: UsoCatalogo.trail,
    dica: 'Motor V4 de 1.158 cc com troca de óleo a cada 15 mil km e revisão de válvulas só aos 60 mil km.',
    psiDianteiro: 33,
    psiTraseiro: 36,
    oleoKm: 15000,
    correnteKm: 1000,
  ),
  ModeloCatalogo(
    marca: 'Triumph',
    modelo: 'Tiger 1200',
    cilindradaCc: 1160,
    kmPorLitro: 15,
    tanqueLitros: 20,
    flex: false,
    uso: UsoCatalogo.trail,
    dica: 'Big trail com cardã na transmissão, sem corrente para lubrificar, e tanque de 20 litros na versão GT.',
    psiDianteiro: 29,
    psiTraseiro: 33,
    oleoKm: 16000,
  ),
  ModeloCatalogo(
    marca: 'BMW',
    modelo: 'R 1200 GS',
    cilindradaCc: 1170,
    kmPorLitro: 16,
    tanqueLitros: 20,
    flex: false,
    uso: UsoCatalogo.trail,
    dica: 'Boxer clássico, apenas gasolina. Tanque 20 L. Cardã, sem corrente. Óleo ~10.000 km.',
    psiDianteiro: 36,
    psiTraseiro: 42,
    oleoKm: 10000,
  ),
  ModeloCatalogo(
    marca: 'Harley-Davidson',
    modelo: 'Pan America 1250',
    cilindradaCc: 1252,
    kmPorLitro: 13,
    tanqueLitros: 21.2,
    flex: false,
    uso: UsoCatalogo.trail,
    dica: 'Única Harley da lista com corrente em vez de correia, o que muda a rotina de manutenção.',
    psiDianteiro: 33,
    psiTraseiro: 36,
    oleoKm: 8000,
    correnteKm: 1000,
  ),
  ModeloCatalogo(
    marca: 'BMW',
    modelo: 'R 1250 GS',
    cilindradaCc: 1254,
    kmPorLitro: 16,
    tanqueLitros: 20,
    flex: false,
    uso: UsoCatalogo.trail,
    dica: 'A GS do motoclube, apenas gasolina. Tanque 20 L. Cardã, sem corrente. Óleo ~10.000 km.',
    psiDianteiro: 36,
    psiTraseiro: 42,
    oleoKm: 10000,
  ),
  ModeloCatalogo(
    marca: 'BMW',
    modelo: 'R 1250 GS Adventure',
    cilindradaCc: 1254,
    kmPorLitro: 16,
    tanqueLitros: 30,
    flex: false,
    uso: UsoCatalogo.trail,
    dica: 'Expedição, apenas gasolina. Tanque 30 L. Cardã, sem corrente. Óleo ~10.000 km.',
    psiDianteiro: 36,
    psiTraseiro: 42,
    oleoKm: 10000,
  ),
  ModeloCatalogo(
    marca: 'BMW',
    modelo: 'R 1300 GS',
    cilindradaCc: 1300,
    kmPorLitro: 16,
    tanqueLitros: 19,
    flex: false,
    uso: UsoCatalogo.trail,
    dica: 'Boxer atual, apenas gasolina. Tanque 19 L. Cardã, sem corrente. Óleo ~10.000 km.',
    psiDianteiro: 36,
    psiTraseiro: 42,
    oleoKm: 10000,
  ),
  ModeloCatalogo(
    marca: 'BMW',
    modelo: 'R 1300 GS Adventure',
    cilindradaCc: 1300,
    kmPorLitro: 17,
    tanqueLitros: 30,
    flex: false,
    uso: UsoCatalogo.trail,
    dica: 'Tanque de 30 litros pensado para viagem longa, e a transmissão é por cardã, sem corrente para lubrificar.',
    psiDianteiro: 36,
    psiTraseiro: 42,
    oleoKm: 10000,
  ),

  // Estrada: custom, clássica e touring de asfalto.
  ModeloCatalogo(
    marca: 'Haojue',
    modelo: 'Master Ride 150',
    cilindradaCc: 149,
    kmPorLitro: 38,
    tanqueLitros: 10.7,
    flex: false,
    uso: UsoCatalogo.estrada,
    dica: 'Custom leve de banco baixo, com tanque de 10,7 litros que limita a autonomia mesmo com consumo baixo.',
    psiDianteiro: 28,
    psiTraseiro: 32,
    oleoKm: 3000,
    correnteKm: 1000,
  ),
  ModeloCatalogo(
    marca: 'Haojue',
    modelo: 'Chopper Road 150',
    cilindradaCc: 149,
    kmPorLitro: 40,
    tanqueLitros: 9,
    flex: false,
    uso: UsoCatalogo.estrada,
    dica: 'Custom de entrada com motor a carburador e tanque de 9 litros. O manual pede óleo novo a cada 3.000 km e corrente lubrificada a cada 1.000 km.',
    psiTraseiro: 32,
    oleoKm: 3000,
    correnteKm: 1000,
  ),
  ModeloCatalogo(
    marca: 'Shineray',
    modelo: 'Iron 250',
    cilindradaCc: 250,
    kmPorLitro: 22,
    tanqueLitros: 14,
    flex: false,
    uso: UsoCatalogo.estrada,
    dica: 'Custom de entrada com ABS nas duas rodas e tanque de 14 litros.',
    psiDianteiro: 26,
    oleoKm: 3000,
    correnteKm: 1000,
  ),
  ModeloCatalogo(
    marca: 'Kawasaki',
    modelo: 'Eliminator 500',
    cilindradaCc: 451,
    kmPorLitro: 27,
    tanqueLitros: 12.5,
    flex: false,
    uso: UsoCatalogo.estrada,
    dica: 'Custom leve de banco baixo, com tanque de 12,5 litros que pede parada mais cedo em viagem.',
    psiDianteiro: 32,
    psiTraseiro: 36,
    oleoKm: 6000,
    correnteKm: 1000,
  ),
  ModeloCatalogo(
    marca: 'Royal Enfield',
    modelo: 'Interceptor 650',
    cilindradaCc: 648,
    kmPorLitro: 22,
    tanqueLitros: 13.7,
    flex: false,
    uso: UsoCatalogo.estrada,
    dica: 'Motor tranquilo aguenta estrada com folga, mas o consumo cai fora da faixa de giro mais econômica.',
    psiDianteiro: 29,
    psiTraseiro: 33,
    oleoKm: 5000,
    correnteKm: 500,
  ),
  ModeloCatalogo(
    marca: 'Royal Enfield',
    modelo: 'Super Meteor 650',
    cilindradaCc: 648,
    kmPorLitro: 20,
    tanqueLitros: 15.7,
    flex: false,
    uso: UsoCatalogo.estrada,
    dica: 'Cruiser pesada para manobra lenta, mas o tanque de 15,7 litros compensa em viagem longa.',
    psiDianteiro: 29,
    psiTraseiro: 33,
    oleoKm: 5000,
    correnteKm: 500,
  ),
  ModeloCatalogo(
    marca: 'Kawasaki',
    modelo: 'Vulcan S',
    cilindradaCc: 649,
    kmPorLitro: 22,
    tanqueLitros: 14,
    flex: false,
    uso: UsoCatalogo.estrada,
    dica: 'Custom de banco baixo com tanque de 14 litros e o motor de 649 cc da linha Ninja.',
    psiDianteiro: 29,
    psiTraseiro: 33,
    oleoKm: 6000,
    correnteKm: 1000,
  ),
  ModeloCatalogo(
    marca: 'Ducati',
    modelo: 'Scrambler Icon',
    cilindradaCc: 803,
    kmPorLitro: 20,
    tanqueLitros: 13.5,
    flex: false,
    uso: UsoCatalogo.estrada,
    dica: 'Moto de estilo retrô com rodas de rua, pensada para uso na cidade e passeio curto.',
    psiDianteiro: 33,
    psiTraseiro: 36,
    oleoKm: 12000,
    correnteKm: 1000,
  ),
  ModeloCatalogo(
    marca: 'Yamaha',
    modelo: 'Tracer 9',
    cilindradaCc: 890,
    kmPorLitro: 18,
    tanqueLitros: 18,
    flex: false,
    uso: UsoCatalogo.estrada,
    dica: 'Tanque de 18 litros dá fôlego para viagem longa, usando a base mecânica da MT-09.',
    psiDianteiro: 33,
    psiTraseiro: 36,
    oleoKm: 6000,
    correnteKm: 1000,
  ),
  ModeloCatalogo(
    marca: 'Harley-Davidson',
    modelo: 'Nightster',
    cilindradaCc: 975,
    kmPorLitro: 20,
    tanqueLitros: 11.7,
    flex: false,
    uso: UsoCatalogo.estrada,
    dica: 'Tanque de 11,7 litros dá autonomia curta, por volta de 250 km, e a transmissão é por correia.',
    psiDianteiro: 36,
    psiTraseiro: 36,
    oleoKm: 8000,
  ),
  ModeloCatalogo(
    marca: 'Triumph',
    modelo: 'Bonneville T120',
    cilindradaCc: 1200,
    kmPorLitro: 17,
    tanqueLitros: 14.5,
    flex: false,
    uso: UsoCatalogo.estrada,
    dica: 'Clássica com acessórios oficiais de bagageiro, mas o tanque de 14,5 litros pede paradas mais cedo em viagem.',
    psiDianteiro: 33,
    psiTraseiro: 36,
    oleoKm: 16000,
    correnteKm: 1000,
  ),
  ModeloCatalogo(
    marca: 'Harley-Davidson',
    modelo: 'Sportster S',
    cilindradaCc: 1252,
    kmPorLitro: 17,
    tanqueLitros: 11.8,
    flex: false,
    uso: UsoCatalogo.estrada,
    dica: 'Tanque pequeno de 11,8 litros e motor de 1.252 cc pedem reabastecimento frequente mesmo andando pouco.',
    psiDianteiro: 36,
    psiTraseiro: 42,
    oleoKm: 8000,
  ),
  ModeloCatalogo(
    marca: 'BMW',
    modelo: 'R 1250 RT',
    cilindradaCc: 1254,
    kmPorLitro: 19,
    tanqueLitros: 25,
    flex: false,
    uso: UsoCatalogo.estrada,
    dica: 'Touring de estrada com tanque de 25 litros e transmissão por cardã, sem corrente para lubrificar.',
    psiDianteiro: 36,
    psiTraseiro: 42,
    oleoKm: 10000,
  ),
  ModeloCatalogo(
    marca: 'BMW',
    modelo: 'R 18',
    cilindradaCc: 1802,
    kmPorLitro: 16,
    tanqueLitros: 16,
    flex: false,
    uso: UsoCatalogo.estrada,
    dica: 'Cruiser pesada com cardã aparente e tanque de 16 litros, então a autonomia é curta para o tamanho da moto.',
    psiDianteiro: 36,
    psiTraseiro: 42,
    oleoKm: 10000,
  ),
  ModeloCatalogo(
    marca: 'Harley-Davidson',
    modelo: 'Fat Boy',
    cilindradaCc: 1868,
    kmPorLitro: 15,
    tanqueLitros: 18.9,
    flex: false,
    uso: UsoCatalogo.estrada,
    dica: 'Motor 114 de 1.868 cc e pneu dianteiro largo pedem mais gasolina na cidade do que na estrada.',
    psiDianteiro: 36,
    psiTraseiro: 38,
    oleoKm: 8000,
  ),
  ModeloCatalogo(
    marca: 'Harley-Davidson',
    modelo: 'Street Glide',
    cilindradaCc: 1923,
    kmPorLitro: 14,
    tanqueLitros: 22.7,
    flex: false,
    uso: UsoCatalogo.estrada,
    dica: 'Carenagem e tanque de 22,7 litros dão mais fôlego de viagem entre as Harley da lista.',
    psiDianteiro: 36,
    psiTraseiro: 40,
    oleoKm: 8000,
  ),

  // Esporte: carenada e naked de alta performance.
  ModeloCatalogo(
    marca: 'Yamaha',
    modelo: 'R3',
    cilindradaCc: 321,
    kmPorLitro: 25,
    tanqueLitros: 14,
    flex: false,
    uso: UsoCatalogo.esporte,
    nomeLista: 'Yamaha YZF-R3',
    dica: 'Esportiva leve, apenas gasolina. Tanque 14 L. Corrente ~1.000 km.',
    psiDianteiro: 29,
    psiTraseiro: 32,
    oleoKm: 6000,
    correnteKm: 1000,
  ),
  ModeloCatalogo(
    marca: 'Yamaha',
    modelo: 'MT-03',
    cilindradaCc: 321,
    kmPorLitro: 26,
    tanqueLitros: 14,
    flex: false,
    uso: UsoCatalogo.esporte,
    dica: 'Naked leve, apenas gasolina. Tanque 14 L. Corrente ~1.000 km.',
    psiDianteiro: 29,
    psiTraseiro: 32,
    oleoKm: 6000,
    correnteKm: 1000,
  ),
  ModeloCatalogo(
    marca: 'Kawasaki',
    modelo: 'Ninja 400',
    cilindradaCc: 399,
    kmPorLitro: 24,
    tanqueLitros: 14,
    flex: false,
    uso: UsoCatalogo.esporte,
    dica: 'Esportiva, apenas gasolina. Tanque 14 L. Corrente ~1.000 km.',
    psiDianteiro: 29,
    psiTraseiro: 32,
    oleoKm: 6000,
    correnteKm: 1000,
  ),
  ModeloCatalogo(
    marca: 'KTM',
    modelo: 'Duke 390',
    cilindradaCc: 399,
    kmPorLitro: 25,
    tanqueLitros: 15,
    flex: false,
    uso: UsoCatalogo.esporte,
    dica: 'Naked, apenas gasolina. Tanque 15 L. Corrente ~1.000 km.',
    psiDianteiro: 29,
    psiTraseiro: 32,
    oleoKm: 6000,
    correnteKm: 1000,
  ),
  ModeloCatalogo(
    marca: 'Kawasaki',
    modelo: 'Z400',
    cilindradaCc: 399,
    kmPorLitro: 20,
    tanqueLitros: 14,
    flex: false,
    uso: UsoCatalogo.esporte,
    dica: 'Tanque de 14 litros pede abastecimento mais frequente, mas o consumo compensa no uso diário.',
    psiDianteiro: 33,
    psiTraseiro: 36,
    oleoKm: 6000,
    correnteKm: 1000,
  ),
  ModeloCatalogo(
    marca: 'Honda',
    modelo: 'CBR 500R',
    cilindradaCc: 471,
    kmPorLitro: 25,
    tanqueLitros: 17.1,
    flex: false,
    uso: UsoCatalogo.esporte,
    dica: 'Esportiva, apenas gasolina. Tanque 17,1 L. Corrente ~1.000 km.',
    psiDianteiro: 29,
    psiTraseiro: 32,
    oleoKm: 6000,
    correnteKm: 1000,
  ),
  ModeloCatalogo(
    marca: 'Honda',
    modelo: 'CB 500F',
    cilindradaCc: 471,
    kmPorLitro: 26,
    tanqueLitros: 16.7,
    flex: false,
    uso: UsoCatalogo.esporte,
    dica: 'Naked média, apenas gasolina. Tanque 16,7 L. Corrente ~1.000 km.',
    psiDianteiro: 29,
    psiTraseiro: 32,
    oleoKm: 6000,
    correnteKm: 1000,
  ),
  ModeloCatalogo(
    marca: 'Kawasaki',
    modelo: 'Ninja ZX-6R',
    cilindradaCc: 636,
    kmPorLitro: 17,
    tanqueLitros: 17,
    flex: false,
    uso: UsoCatalogo.esporte,
    dica: 'Supersportiva de pista com tanque de 17 litros, o que ajuda na autonomia do dia a dia.',
    psiDianteiro: 36,
    psiTraseiro: 42,
    oleoKm: 6000,
    correnteKm: 1000,
  ),
  ModeloCatalogo(
    marca: 'Honda',
    modelo: 'CB 650R',
    cilindradaCc: 649,
    kmPorLitro: 16.5,
    tanqueLitros: 15.4,
    flex: false,
    uso: UsoCatalogo.esporte,
    dica: 'Naked de quatro cilindros com tanque de 15,4 litros, que rende pouco quando a moto anda em giro alto.',
    psiDianteiro: 33,
    psiTraseiro: 36,
    oleoKm: 6000,
    correnteKm: 1000,
  ),
  ModeloCatalogo(
    marca: 'Kawasaki',
    modelo: 'Z650',
    cilindradaCc: 649,
    kmPorLitro: 21,
    tanqueLitros: 15,
    flex: false,
    uso: UsoCatalogo.esporte,
    dica: 'Naked de 649 cc sem carenagem, com tanque de 15 litros e consumo melhor em rodovia.',
    psiDianteiro: 33,
    psiTraseiro: 36,
    oleoKm: 6000,
    correnteKm: 1000,
  ),
  ModeloCatalogo(
    marca: 'Kawasaki',
    modelo: 'Ninja 650',
    cilindradaCc: 649,
    kmPorLitro: 23,
    tanqueLitros: 15,
    flex: false,
    uso: UsoCatalogo.esporte,
    dica: 'Esportiva carenada de entrada, fácil de pilotar mesmo por quem está começando.',
    psiDianteiro: 33,
    psiTraseiro: 36,
    oleoKm: 6000,
    correnteKm: 1000,
  ),
  ModeloCatalogo(
    marca: 'Yamaha',
    modelo: 'MT-07',
    cilindradaCc: 689,
    kmPorLitro: 21,
    tanqueLitros: 14,
    flex: false,
    uso: UsoCatalogo.esporte,
    dica: 'Motor de dois cilindros com torque forte em baixa rotação, referência de entrada nas nakeds médias.',
    psiDianteiro: 33,
    psiTraseiro: 36,
    oleoKm: 5000,
    correnteKm: 1000,
  ),
  ModeloCatalogo(
    marca: 'Honda',
    modelo: 'CB 750 Hornet',
    cilindradaCc: 755,
    kmPorLitro: 23,
    tanqueLitros: 15.2,
    flex: false,
    uso: UsoCatalogo.esporte,
    dica: 'Naked de 755 cc com tanque de 15,2 litros, que dá cerca de 350 km em uso misto.',
    psiDianteiro: 33,
    psiTraseiro: 36,
    oleoKm: 6000,
    correnteKm: 1000,
  ),
  ModeloCatalogo(
    marca: 'Triumph',
    modelo: 'Street Triple 765',
    cilindradaCc: 765,
    kmPorLitro: 20,
    tanqueLitros: 15,
    flex: false,
    uso: UsoCatalogo.esporte,
    dica: 'Naked esportiva de alta performance, com tanque de 15 litros que limita a autonomia em viagem.',
    psiDianteiro: 36,
    psiTraseiro: 36,
    oleoKm: 12000,
    correnteKm: 1000,
  ),
  ModeloCatalogo(
    marca: 'Suzuki',
    modelo: 'GSX-8S',
    cilindradaCc: 776,
    kmPorLitro: 21,
    tanqueLitros: 14,
    flex: false,
    uso: UsoCatalogo.esporte,
    dica: 'Painel colorido e eletrônica moderna, e os 83 cv pedem atenção redobrada em piso molhado.',
    psiDianteiro: 33,
    psiTraseiro: 36,
    oleoKm: 6000,
    correnteKm: 1000,
  ),
  ModeloCatalogo(
    marca: 'Yamaha',
    modelo: 'MT-09',
    cilindradaCc: 890,
    kmPorLitro: 20,
    tanqueLitros: 14,
    flex: false,
    uso: UsoCatalogo.esporte,
    dica: 'Motor de três cilindros bem mais potente que a MT-07, consumo mais alto compensado pelo desempenho.',
    psiDianteiro: 36,
    psiTraseiro: 36,
    oleoKm: 6000,
    correnteKm: 1000,
  ),
  ModeloCatalogo(
    marca: 'Ducati',
    modelo: 'Panigale V2',
    cilindradaCc: 890,
    kmPorLitro: 16,
    tanqueLitros: 15,
    flex: false,
    uso: UsoCatalogo.esporte,
    dica: 'Superesportiva carenada com tanque de 15 litros, feita para pista e trecho curto de estrada.',
    psiDianteiro: 33,
    psiTraseiro: 36,
    oleoKm: 15000,
    correnteKm: 1000,
  ),
  ModeloCatalogo(
    marca: 'Ducati',
    modelo: 'Monster',
    cilindradaCc: 937,
    kmPorLitro: 17,
    tanqueLitros: 14,
    flex: false,
    uso: UsoCatalogo.esporte,
    dica: 'Naked de alta performance com 111 cv e tanque de 14 litros, pede parada mais cedo que uma trail.',
    psiDianteiro: 33,
    psiTraseiro: 36,
    oleoKm: 12000,
    correnteKm: 1000,
  ),
  ModeloCatalogo(
    marca: 'Kawasaki',
    modelo: 'Z900',
    cilindradaCc: 948,
    kmPorLitro: 20,
    tanqueLitros: 17,
    flex: false,
    uso: UsoCatalogo.esporte,
    dica: 'Naked de 124 cv, o consumo melhora bastante em rodovia com pilotagem mais tranquila.',
    psiDianteiro: 36,
    psiTraseiro: 36,
    oleoKm: 6000,
    correnteKm: 1000,
  ),
  ModeloCatalogo(
    marca: 'Kawasaki',
    modelo: 'Ninja ZX-10R',
    cilindradaCc: 998,
    kmPorLitro: 14,
    tanqueLitros: 17,
    flex: false,
    uso: UsoCatalogo.esporte,
    dica: 'Superbike de alta cilindrada, consumo baixo é normal e o tanque de 17 litros limita a autonomia em viagem.',
    psiDianteiro: 36,
    psiTraseiro: 42,
    oleoKm: 6000,
    correnteKm: 1000,
  ),
  ModeloCatalogo(
    marca: 'BMW',
    modelo: 'S 1000 RR',
    cilindradaCc: 999,
    kmPorLitro: 12,
    tanqueLitros: 16.5,
    flex: false,
    uso: UsoCatalogo.esporte,
    dica: 'Esportiva pura, o consumo cai bastante em pilotagem forte ou pista, então o tanque de 16,5 litros rende menos do que parece.',
    psiDianteiro: 36,
    psiTraseiro: 42,
    oleoKm: 10000,
    correnteKm: 1000,
  ),
  ModeloCatalogo(
    marca: 'Suzuki',
    modelo: 'Hayabusa',
    cilindradaCc: 1340,
    kmPorLitro: 14,
    tanqueLitros: 20,
    flex: false,
    uso: UsoCatalogo.esporte,
    dica: 'Hipersportiva com tanque de 20 litros, que ajuda a compensar o consumo alto em velocidade.',
    psiDianteiro: 36,
    psiTraseiro: 42,
    oleoKm: 6000,
    correnteKm: 1000,
  ),
];
