/// Catálogo local com marca, modelo, tanque e média (gasolina e álcool).
///
/// Valores de uso misto (cidade e estrada), fora de bancada.
/// O piloto ajusta depois da própria média. Sem FIPE e sem placa.
enum UsoCatalogo { cidade, estrada, esporte }

class ModeloCatalogo {
  const ModeloCatalogo({
    required this.marca,
    required this.modelo,
    required this.cilindradaCc,
    required this.kmPorLitro,
    required this.tanqueLitros,
    required this.uso,
    this.kmPorLitroAlcool,
    this.flex = true,
    this.dica = '',
    this.nomeLista,
    this.psiDianteiro = 25,
    this.psiTraseiro = 29,
    this.oleoKm = 4000,
    this.correnteKm,
  });

  final String marca;
  final String modelo;
  final int cilindradaCc;

  /// Gasolina, uso misto.
  final double kmPorLitro;

  /// Álcool. Null = moto só a gasolina.
  final double? kmPorLitroAlcool;

  final double tanqueLitros;
  final bool flex;
  final String dica;
  final UsoCatalogo uso;

  /// Texto da lista, se o modelo precisar de apelido (Fan, Titan…).
  final String? nomeLista;

  final int psiDianteiro;
  final int psiTraseiro;
  final int oleoKm;

  /// Null = scooter / CVT / cardã, sem corrente.
  final int? correnteKm;

  String get rotulo => nomeLista ?? '$marca $modelo';

  /// Silhueta local (desenho nosso, sem foto de fabricante).
  String get assetSilhueta {
    if (uso == UsoCatalogo.esporte) {
      return 'assets/catalogo/esporte.png';
    }
    if (correnteKm == null && uso == UsoCatalogo.cidade) {
      return 'assets/catalogo/scooter.png';
    }
    if (uso == UsoCatalogo.estrada) {
      return 'assets/catalogo/estrada.png';
    }
    return 'assets/catalogo/cidade.png';
  }
}

List<ModeloCatalogo> catalogoFiltrado(UsoCatalogo? uso) {
  if (uso == null) return catalogoMotos;
  return [for (final m in catalogoMotos) if (m.uso == uso) m];
}

const List<ModeloCatalogo> catalogoMotos = [
  ModeloCatalogo(
    marca: 'Honda',
    modelo: 'Pop 110i',
    cilindradaCc: 110,
    kmPorLitro: 49,
    tanqueLitros: 4.2,
    flex: false,
    uso: UsoCatalogo.cidade,
    dica:
        'Só gasolina. Tanque 4,2 L, enche mais vezes e rende bem no litro. Corrente cerca de 1.000 km.',
    psiDianteiro: 25,
    psiTraseiro: 32,
    correnteKm: 1000,
  ),
  ModeloCatalogo(
    marca: 'Honda',
    modelo: 'Biz 125',
    cilindradaCc: 124,
    kmPorLitro: 48,
    kmPorLitroAlcool: 37,
    tanqueLitros: 5,
    uso: UsoCatalogo.cidade,
    dica: 'FlexOne, semiautomática. Tanque 5 L. No álcool a média cai ~25%. Corrente ~1.000 km.',
    psiDianteiro: 25,
    psiTraseiro: 32,
    correnteKm: 1000,
  ),
  ModeloCatalogo(
    marca: 'Honda',
    modelo: 'Elite 125',
    cilindradaCc: 124,
    kmPorLitro: 42,
    tanqueLitros: 5.3,
    flex: false,
    uso: UsoCatalogo.cidade,
    dica:
        'Scooter só a gasolina. Tanque 5,3 L. Idling Stop desliga o motor no farol.',
    psiDianteiro: 25,
    psiTraseiro: 32,
  ),
  ModeloCatalogo(
    marca: 'Honda',
    modelo: 'CG 160',
    cilindradaCc: 163,
    kmPorLitro: 41,
    kmPorLitroAlcool: 35,
    tanqueLitros: 16.1,
    uso: UsoCatalogo.cidade,
    nomeLista: 'Honda CG 160 (Fan / Titan / Start)',
    dica:
        'Flex (Fan, Titan ou Start). Tanque 16,1 L, autonomia longa. Óleo ~4.000 km. Corrente ~1.000 km. Pneu 25/29 PSI.',
    correnteKm: 1000,
  ),
  ModeloCatalogo(
    marca: 'Honda',
    modelo: 'PCX 160',
    cilindradaCc: 157,
    kmPorLitro: 40,
    tanqueLitros: 8.1,
    flex: false,
    uso: UsoCatalogo.cidade,
    dica: 'Scooter só a gasolina. Tanque 8,1 L. Este modelo não tem álcool no tanque.',
    psiDianteiro: 25,
    psiTraseiro: 32,
  ),
  ModeloCatalogo(
    marca: 'Honda',
    modelo: 'ADV 160',
    cilindradaCc: 157,
    kmPorLitro: 38,
    tanqueLitros: 8.1,
    flex: false,
    uso: UsoCatalogo.cidade,
    dica: 'Scooter aventureira, só gasolina. Mesmo tanque do PCX (8,1 L).',
    psiDianteiro: 25,
    psiTraseiro: 32,
  ),
  ModeloCatalogo(
    marca: 'Honda',
    modelo: 'CB 300F Twister',
    cilindradaCc: 294,
    kmPorLitro: 29,
    kmPorLitroAlcool: 22,
    tanqueLitros: 14.1,
    uso: UsoCatalogo.cidade,
    dica: 'Flex. Cidade e viagem curta. No álcool a média cai. Corrente ~1.000 km.',
    correnteKm: 1000,
  ),
  ModeloCatalogo(
    marca: 'Yamaha',
    modelo: 'Factor 150',
    cilindradaCc: 149,
    kmPorLitro: 42,
    kmPorLitroAlcool: 32,
    tanqueLitros: 15.4,
    uso: UsoCatalogo.cidade,
    dica: 'BlueFlex. Tanque 15,4 L, poucas paradas no posto. Corrente ~1.000 km.',
    correnteKm: 1000,
  ),
  ModeloCatalogo(
    marca: 'Yamaha',
    modelo: 'Fazer 150',
    cilindradaCc: 150,
    kmPorLitro: 40,
    kmPorLitroAlcool: 30,
    tanqueLitros: 15.2,
    uso: UsoCatalogo.cidade,
    dica: 'BlueFlex, street. Tanque 15,2 L. No álcool a média cai. Corrente ~1.000 km.',
    correnteKm: 1000,
  ),
  ModeloCatalogo(
    marca: 'Yamaha',
    modelo: 'FZ15',
    cilindradaCc: 149,
    kmPorLitro: 40,
    kmPorLitroAlcool: 30,
    tanqueLitros: 11.9,
    uso: UsoCatalogo.cidade,
    dica: 'BlueFlex, street. Tanque 11,9 L. ABS na dianteira nas versões novas. Corrente ~1.000 km.',
    correnteKm: 1000,
  ),
  ModeloCatalogo(
    marca: 'Yamaha',
    modelo: 'Fazer 250',
    cilindradaCc: 249,
    kmPorLitro: 32,
    tanqueLitros: 14.2,
    flex: false,
    uso: UsoCatalogo.cidade,
    nomeLista: 'Yamaha Fazer 250 / FZ25',
    dica: 'Só gasolina. Tanque 14,2 L. Este motor não usa álcool. Corrente ~1.000 km.',
    correnteKm: 1000,
  ),
  ModeloCatalogo(
    marca: 'Yamaha',
    modelo: 'NMax 160',
    cilindradaCc: 155,
    kmPorLitro: 38,
    tanqueLitros: 7.1,
    flex: false,
    uso: UsoCatalogo.cidade,
    dica: 'Scooter só gasolina. Tanque 7,1 L, autonomia menor que o PCX.',
    psiDianteiro: 25,
    psiTraseiro: 32,
  ),
  ModeloCatalogo(
    marca: 'Yamaha',
    modelo: 'ZR Hybrid',
    cilindradaCc: 125,
    kmPorLitro: 48,
    tanqueLitros: 5.2,
    flex: false,
    uso: UsoCatalogo.cidade,
    dica:
        'Scooter híbrida, só gasolina. Tanque 5,2 L. Stop & Start ajuda no farol.',
    psiDianteiro: 25,
    psiTraseiro: 32,
  ),
  ModeloCatalogo(
    marca: 'Triumph',
    modelo: 'Speed 400',
    cilindradaCc: 398,
    kmPorLitro: 28,
    tanqueLitros: 13,
    flex: false,
    uso: UsoCatalogo.cidade,
    dica: 'Naked só gasolina. Tanque 13 L. Cidade e trecho curto. Corrente ~1.000 km.',
    oleoKm: 6000,
    correnteKm: 1000,
  ),
  ModeloCatalogo(
    marca: 'Honda',
    modelo: 'NXR 160 Bros',
    cilindradaCc: 163,
    kmPorLitro: 35,
    kmPorLitroAlcool: 28,
    tanqueLitros: 12,
    uso: UsoCatalogo.estrada,
    dica: 'Flex, trail. Tanque interno 12 L. No álcool a média cai. Pneu 22/29 PSI. Corrente ~1.000 km.',
    psiDianteiro: 22,
    correnteKm: 1000,
  ),
  ModeloCatalogo(
    marca: 'Honda',
    modelo: 'XRE 190',
    cilindradaCc: 184,
    kmPorLitro: 36,
    kmPorLitroAlcool: 28,
    tanqueLitros: 12,
    uso: UsoCatalogo.estrada,
    dica: 'Flex, trail leve. Mesmo tanque da Bros, um pouco mais de fôlego. Pneu 22/29 PSI.',
    psiDianteiro: 22,
    correnteKm: 1000,
  ),
  ModeloCatalogo(
    marca: 'Honda',
    modelo: 'XRE 300',
    cilindradaCc: 292,
    kmPorLitro: 26,
    kmPorLitroAlcool: 20,
    tanqueLitros: 14,
    uso: UsoCatalogo.estrada,
    dica:
        'Flex, trail. Tanque 14 L. Óleo e relação pedem atenção no uso de terra. Pneu 22/29 PSI.',
    psiDianteiro: 22,
    correnteKm: 1000,
  ),
  ModeloCatalogo(
    marca: 'Honda',
    modelo: 'Sahara 300',
    cilindradaCc: 294,
    kmPorLitro: 30,
    kmPorLitroAlcool: 24,
    tanqueLitros: 13.8,
    uso: UsoCatalogo.estrada,
    dica:
        'Flex, sucessor da XRE 300. Tanque 13,8 L, uns 400 km na gasolina. Pneu 22/29 PSI.',
    psiDianteiro: 22,
    correnteKm: 1000,
  ),
  ModeloCatalogo(
    marca: 'Honda',
    modelo: 'Tornado 300',
    cilindradaCc: 294,
    kmPorLitro: 29,
    kmPorLitroAlcool: 23,
    tanqueLitros: 13.8,
    uso: UsoCatalogo.estrada,
    nomeLista: 'Honda XR 300 Tornado',
    dica:
        'Flex, irmã da Sahara com foco em terra. Mesmo tanque 13,8 L e motor 300. Pneu 22/29 PSI.',
    psiDianteiro: 22,
    correnteKm: 1000,
  ),
  ModeloCatalogo(
    marca: 'Honda',
    modelo: 'CB 500X',
    cilindradaCc: 471,
    kmPorLitro: 25,
    tanqueLitros: 17.5,
    flex: false,
    uso: UsoCatalogo.estrada,
    nomeLista: 'Honda CB 500X / NX 500',
    dica: 'Trail média, só gasolina. Tanque 17,5 L. Óleo ~6.000 km. Pneu 22/29 PSI.',
    psiDianteiro: 22,
    oleoKm: 6000,
    correnteKm: 1000,
  ),
  ModeloCatalogo(
    marca: 'Honda',
    modelo: 'NC 750X',
    cilindradaCc: 745,
    kmPorLitro: 26,
    tanqueLitros: 14.1,
    flex: false,
    uso: UsoCatalogo.estrada,
    dica:
        'Crossover, só gasolina. Tanque 14,1 L, o resto é porta-capacete. Óleo ~6.000 km.',
    psiDianteiro: 29,
    psiTraseiro: 36,
    oleoKm: 6000,
    correnteKm: 1000,
  ),
  ModeloCatalogo(
    marca: 'Honda',
    modelo: 'XL 750 Transalp',
    cilindradaCc: 755,
    kmPorLitro: 22,
    tanqueLitros: 16.9,
    flex: false,
    uso: UsoCatalogo.estrada,
    dica: 'Trail de viagem, só gasolina. Tanque 16,9 L. Pneu 22/29 PSI. Óleo ~6.000 km.',
    psiDianteiro: 22,
    oleoKm: 6000,
    correnteKm: 1000,
  ),
  ModeloCatalogo(
    marca: 'Honda',
    modelo: 'CRF 1100 Africa Twin',
    cilindradaCc: 1084,
    kmPorLitro: 18,
    tanqueLitros: 18.8,
    flex: false,
    uso: UsoCatalogo.estrada,
    dica: 'Big trail, só gasolina. Tanque 18,8 L. Viagem longa. Óleo ~6.000 km.',
    psiDianteiro: 22,
    oleoKm: 6000,
    correnteKm: 1000,
  ),
  ModeloCatalogo(
    marca: 'Yamaha',
    modelo: 'Crosser 150',
    cilindradaCc: 149,
    kmPorLitro: 38,
    kmPorLitroAlcool: 30,
    tanqueLitros: 12,
    uso: UsoCatalogo.estrada,
    dica: 'BlueFlex, trail. Tanque 12 L. No álcool a média cai. Pneu 22/29 PSI.',
    psiDianteiro: 22,
    correnteKm: 1000,
  ),
  ModeloCatalogo(
    marca: 'Yamaha',
    modelo: 'Ténéré 250',
    cilindradaCc: 249,
    kmPorLitro: 28,
    tanqueLitros: 16,
    flex: false,
    uso: UsoCatalogo.estrada,
    nomeLista: 'Yamaha XTZ 250 Ténéré',
    dica: 'Trail clássica, só gasolina. Tanque 16 L. Pneu 22/29 PSI. Corrente ~1.000 km.',
    psiDianteiro: 22,
    correnteKm: 1000,
  ),
  ModeloCatalogo(
    marca: 'Yamaha',
    modelo: 'Lander 250',
    cilindradaCc: 249,
    kmPorLitro: 32,
    tanqueLitros: 13.6,
    flex: false,
    uso: UsoCatalogo.estrada,
    dica:
        'Trail só a gasolina. Tanque 13,6 L. Relação e pneu traseiro gastam cedo na terra. Pneu 22/29 PSI.',
    psiDianteiro: 22,
    correnteKm: 1000,
  ),
  ModeloCatalogo(
    marca: 'Yamaha',
    modelo: 'Ténéré 700',
    cilindradaCc: 689,
    kmPorLitro: 20,
    tanqueLitros: 16,
    flex: false,
    uso: UsoCatalogo.estrada,
    dica: 'Big trail, só gasolina. Tanque 16 L. Pneu 22/29 PSI. Óleo ~6.000 km.',
    psiDianteiro: 22,
    oleoKm: 6000,
    correnteKm: 1000,
  ),
  ModeloCatalogo(
    marca: 'Royal Enfield',
    modelo: 'Hunter 350',
    cilindradaCc: 349,
    kmPorLitro: 32,
    tanqueLitros: 13,
    flex: false,
    uso: UsoCatalogo.estrada,
    dica: 'Só gasolina. Tanque 13 L. Entrada da Royal. Óleo ~6.000 km.',
    psiDianteiro: 25,
    psiTraseiro: 32,
    oleoKm: 6000,
    correnteKm: 1000,
  ),
  ModeloCatalogo(
    marca: 'Royal Enfield',
    modelo: 'Classic 350',
    cilindradaCc: 349,
    kmPorLitro: 30,
    tanqueLitros: 13,
    flex: false,
    uso: UsoCatalogo.estrada,
    dica: 'Custom, só gasolina. Tanque 13 L. Viagem curta e média. Óleo ~6.000 km.',
    psiDianteiro: 25,
    psiTraseiro: 32,
    oleoKm: 6000,
    correnteKm: 1000,
  ),
  ModeloCatalogo(
    marca: 'Royal Enfield',
    modelo: 'Meteor 350',
    cilindradaCc: 349,
    kmPorLitro: 30,
    tanqueLitros: 15,
    flex: false,
    uso: UsoCatalogo.estrada,
    dica: 'Custom, só gasolina. Tanque 15 L, mais autonomia que a Classic. Óleo ~6.000 km.',
    psiDianteiro: 25,
    psiTraseiro: 32,
    oleoKm: 6000,
    correnteKm: 1000,
  ),
  ModeloCatalogo(
    marca: 'Royal Enfield',
    modelo: 'Himalayan 450',
    cilindradaCc: 452,
    kmPorLitro: 26,
    tanqueLitros: 17,
    flex: false,
    uso: UsoCatalogo.estrada,
    dica: 'Trail, só gasolina. Tanque 17 L. Uso misto. Pneu 22/29 PSI. Óleo ~6.000 km.',
    psiDianteiro: 22,
    oleoKm: 6000,
    correnteKm: 1000,
  ),
  ModeloCatalogo(
    marca: 'CFMOTO',
    modelo: 'Ibex 450',
    cilindradaCc: 450,
    kmPorLitro: 24,
    tanqueLitros: 17.5,
    flex: false,
    uso: UsoCatalogo.estrada,
    dica: 'Trail, só gasolina. Tanque 17,5 L. Pneu 22/29 PSI. Óleo ~6.000 km.',
    psiDianteiro: 22,
    oleoKm: 6000,
    correnteKm: 1000,
  ),
  ModeloCatalogo(
    marca: 'CFMOTO',
    modelo: 'Ibex 700',
    cilindradaCc: 693,
    kmPorLitro: 20,
    tanqueLitros: 20,
    flex: false,
    uso: UsoCatalogo.estrada,
    dica: 'Crossover, só gasolina. Tanque 20 L. Óleo ~6.000 km. Corrente ~1.000 km.',
    psiDianteiro: 29,
    psiTraseiro: 36,
    oleoKm: 6000,
    correnteKm: 1000,
  ),
  ModeloCatalogo(
    marca: 'Suzuki',
    modelo: 'V-Strom 650',
    cilindradaCc: 645,
    kmPorLitro: 20,
    tanqueLitros: 20,
    flex: false,
    uso: UsoCatalogo.estrada,
    dica: 'Big trail, só gasolina. Tanque 20 L. Uso misto. Óleo ~6.000 km.',
    psiDianteiro: 29,
    psiTraseiro: 36,
    oleoKm: 6000,
    correnteKm: 1000,
  ),
  ModeloCatalogo(
    marca: 'Suzuki',
    modelo: 'V-Strom 800DE',
    cilindradaCc: 776,
    kmPorLitro: 19,
    tanqueLitros: 20,
    flex: false,
    uso: UsoCatalogo.estrada,
    dica: 'Big trail, só gasolina. Tanque 20 L. Aro 21 na dianteira. Óleo ~6.000 km.',
    psiDianteiro: 22,
    oleoKm: 6000,
    correnteKm: 1000,
  ),
  ModeloCatalogo(
    marca: 'Kawasaki',
    modelo: 'Versys-X 300',
    cilindradaCc: 296,
    kmPorLitro: 22,
    tanqueLitros: 17,
    flex: false,
    uso: UsoCatalogo.estrada,
    dica: 'Trail leve, só gasolina. Tanque 17 L. Pneu 22/29 PSI. Óleo ~6.000 km.',
    psiDianteiro: 22,
    oleoKm: 6000,
    correnteKm: 1000,
  ),
  ModeloCatalogo(
    marca: 'Kawasaki',
    modelo: 'Versys 650',
    cilindradaCc: 649,
    kmPorLitro: 18,
    tanqueLitros: 21,
    flex: false,
    uso: UsoCatalogo.estrada,
    dica: 'Touring, só gasolina. Tanque 21 L. Óleo ~6.000 km. Corrente ~1.000 km.',
    psiDianteiro: 29,
    psiTraseiro: 36,
    oleoKm: 6000,
    correnteKm: 1000,
  ),
  ModeloCatalogo(
    marca: 'Triumph',
    modelo: 'Scrambler 400 X',
    cilindradaCc: 398,
    kmPorLitro: 26,
    tanqueLitros: 13,
    flex: false,
    uso: UsoCatalogo.estrada,
    dica: 'Scrambler, só gasolina. Tanque 13 L. Trecho de terra leve. Óleo ~6.000 km.',
    psiDianteiro: 22,
    oleoKm: 6000,
    correnteKm: 1000,
  ),
  ModeloCatalogo(
    marca: 'Triumph',
    modelo: 'Tiger 900',
    cilindradaCc: 888,
    kmPorLitro: 18,
    tanqueLitros: 20,
    flex: false,
    uso: UsoCatalogo.estrada,
    dica: 'Big trail, só gasolina. Tanque 20 L. Viagem longa. Óleo ~6.000 km.',
    psiDianteiro: 22,
    oleoKm: 6000,
    correnteKm: 1000,
  ),
  ModeloCatalogo(
    marca: 'BMW',
    modelo: 'G 310 GS',
    cilindradaCc: 313,
    kmPorLitro: 26,
    tanqueLitros: 11,
    flex: false,
    uso: UsoCatalogo.estrada,
    dica:
        'Entrada da família GS, só gasolina. Tanque 11 L. Corrente ~1.000 km. Óleo ~6.000 km.',
    psiDianteiro: 33,
    psiTraseiro: 36,
    oleoKm: 6000,
    correnteKm: 1000,
  ),
  ModeloCatalogo(
    marca: 'BMW',
    modelo: 'F 750 GS',
    cilindradaCc: 853,
    kmPorLitro: 20,
    tanqueLitros: 15,
    flex: false,
    uso: UsoCatalogo.estrada,
    dica:
        'Trail média, só gasolina. Tanque 15 L. Mesmo motor da F 850, mais manso. Corrente ~1.000 km.',
    psiDianteiro: 36,
    psiTraseiro: 42,
    oleoKm: 10000,
    correnteKm: 1000,
  ),
  ModeloCatalogo(
    marca: 'BMW',
    modelo: 'F 850 GS',
    cilindradaCc: 853,
    kmPorLitro: 18,
    tanqueLitros: 15,
    flex: false,
    uso: UsoCatalogo.estrada,
    dica: 'Trail média, só gasolina. Tanque 15 L. Corrente ~1.000 km. Óleo ~10.000 km.',
    psiDianteiro: 36,
    psiTraseiro: 42,
    oleoKm: 10000,
    correnteKm: 1000,
  ),
  ModeloCatalogo(
    marca: 'BMW',
    modelo: 'F 850 GS Adventure',
    cilindradaCc: 853,
    kmPorLitro: 18,
    tanqueLitros: 23,
    flex: false,
    uso: UsoCatalogo.estrada,
    dica:
        'Irmã da F 850 com tanque 23 L. Só gasolina. Corrente ~1.000 km. Óleo ~10.000 km.',
    psiDianteiro: 36,
    psiTraseiro: 42,
    oleoKm: 10000,
    correnteKm: 1000,
  ),
  ModeloCatalogo(
    marca: 'BMW',
    modelo: 'F 900 GS',
    cilindradaCc: 895,
    kmPorLitro: 18,
    tanqueLitros: 14.5,
    flex: false,
    uso: UsoCatalogo.estrada,
    dica: 'Sucessora da F 850, só gasolina. Tanque 14,5 L. Corrente ~1.000 km.',
    psiDianteiro: 36,
    psiTraseiro: 42,
    oleoKm: 10000,
    correnteKm: 1000,
  ),
  ModeloCatalogo(
    marca: 'BMW',
    modelo: 'R 1200 GS',
    cilindradaCc: 1170,
    kmPorLitro: 16,
    tanqueLitros: 20,
    flex: false,
    uso: UsoCatalogo.estrada,
    dica:
        'Boxer clássico, só gasolina. Tanque 20 L. Cardã, sem corrente. Óleo ~10.000 km.',
    psiDianteiro: 36,
    psiTraseiro: 42,
    oleoKm: 10000,
  ),
  ModeloCatalogo(
    marca: 'BMW',
    modelo: 'R 1250 GS',
    cilindradaCc: 1254,
    kmPorLitro: 16,
    tanqueLitros: 20,
    flex: false,
    uso: UsoCatalogo.estrada,
    dica:
        'A GS do motoclube, só gasolina. Tanque 20 L. Cardã, sem corrente. Óleo ~10.000 km.',
    psiDianteiro: 36,
    psiTraseiro: 42,
    oleoKm: 10000,
  ),
  ModeloCatalogo(
    marca: 'BMW',
    modelo: 'R 1250 GS Adventure',
    cilindradaCc: 1254,
    kmPorLitro: 16,
    tanqueLitros: 30,
    flex: false,
    uso: UsoCatalogo.estrada,
    dica:
        'Expedição, só gasolina. Tanque 30 L. Cardã, sem corrente. Óleo ~10.000 km.',
    psiDianteiro: 36,
    psiTraseiro: 42,
    oleoKm: 10000,
  ),
  ModeloCatalogo(
    marca: 'BMW',
    modelo: 'R 1300 GS',
    cilindradaCc: 1300,
    kmPorLitro: 16,
    tanqueLitros: 19,
    flex: false,
    uso: UsoCatalogo.estrada,
    dica:
        'Boxer atual, só gasolina. Tanque 19 L. Cardã, sem corrente. Óleo ~10.000 km.',
    psiDianteiro: 36,
    psiTraseiro: 42,
    oleoKm: 10000,
  ),
  ModeloCatalogo(
    marca: 'Honda',
    modelo: 'CBR 500R',
    cilindradaCc: 471,
    kmPorLitro: 25,
    tanqueLitros: 17.1,
    flex: false,
    uso: UsoCatalogo.esporte,
    dica: 'Esportiva, só gasolina. Tanque 17,1 L. Corrente ~1.000 km.',
    psiDianteiro: 29,
    psiTraseiro: 32,
    oleoKm: 6000,
    correnteKm: 1000,
  ),
  ModeloCatalogo(
    marca: 'Honda',
    modelo: 'CB 500F',
    cilindradaCc: 471,
    kmPorLitro: 26,
    tanqueLitros: 16.7,
    flex: false,
    uso: UsoCatalogo.esporte,
    dica: 'Naked média, só gasolina. Tanque 16,7 L. Corrente ~1.000 km.',
    psiDianteiro: 29,
    psiTraseiro: 32,
    oleoKm: 6000,
    correnteKm: 1000,
  ),
  ModeloCatalogo(
    marca: 'Yamaha',
    modelo: 'R3',
    cilindradaCc: 321,
    kmPorLitro: 25,
    tanqueLitros: 14,
    flex: false,
    uso: UsoCatalogo.esporte,
    nomeLista: 'Yamaha YZF-R3',
    dica: 'Esportiva leve, só gasolina. Tanque 14 L. Corrente ~1.000 km.',
    psiDianteiro: 29,
    psiTraseiro: 32,
    oleoKm: 6000,
    correnteKm: 1000,
  ),
  ModeloCatalogo(
    marca: 'Yamaha',
    modelo: 'MT-03',
    cilindradaCc: 321,
    kmPorLitro: 26,
    tanqueLitros: 14,
    flex: false,
    uso: UsoCatalogo.esporte,
    dica: 'Naked leve, só gasolina. Tanque 14 L. Corrente ~1.000 km.',
    psiDianteiro: 29,
    psiTraseiro: 32,
    oleoKm: 6000,
    correnteKm: 1000,
  ),
  ModeloCatalogo(
    marca: 'Kawasaki',
    modelo: 'Ninja 400',
    cilindradaCc: 399,
    kmPorLitro: 24,
    tanqueLitros: 14,
    flex: false,
    uso: UsoCatalogo.esporte,
    dica: 'Esportiva, só gasolina. Tanque 14 L. Corrente ~1.000 km.',
    psiDianteiro: 29,
    psiTraseiro: 32,
    oleoKm: 6000,
    correnteKm: 1000,
  ),
  ModeloCatalogo(
    marca: 'KTM',
    modelo: 'Duke 390',
    cilindradaCc: 399,
    kmPorLitro: 25,
    tanqueLitros: 15,
    flex: false,
    uso: UsoCatalogo.esporte,
    dica: 'Naked, só gasolina. Tanque 15 L. Corrente ~1.000 km.',
    psiDianteiro: 29,
    psiTraseiro: 32,
    oleoKm: 6000,
    correnteKm: 1000,
  ),
];
