# This file configures the analyzer, which statically analyzes Dart code to
# check for errors, warnings, and lints.
#
# https://dart.dev/guides/language/analysis-options

include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - build/**
    - android/**
    - ios/**
    - web/**
    - windows/**
    - macos/**
    - linux/**
    - lib/**/*.g.dart

linter:
  rules:
    prefer_single_quotes: true
    avoid_print: true
    unnecessary_this: true
    always_declare_return_types: true
    prefer_final_fields: true
    avoid_empty_else: true
    cancel_subscriptions: true
    close_sinks: true
