name: life_and_roads
description: Caderneta digital de uma motocicleta. Ficha, manutenção, viagem e GPS.
publish_to: 'none'
version: 1.2.0+5

environment:
  sdk: ^3.13.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.5.3
  flutter_secure_storage: ^11.0.0
  http: ^1.5.0
  flutter_local_notifications: ^19.5.0
  timezone: ^0.10.1
  flutter_map: ^8.2.2
  latlong2: ^0.9.1
  geolocator: ^14.0.2
  google_fonts: ^6.3.2
  image_picker: ^1.2.0
  flutter_riverpod: ^2.6.1
  drift: ^2.28.0
  drift_flutter: ^0.2.7
  path_provider: ^2.1.5
  path: ^1.9.1
  sqlite3: ^2.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4
  drift_dev: ^2.28.0
  build_runner: ^2.4.15

flutter:
  uses-material-design: true
  assets:
    - assets/lr.png
    - assets/catalogo/

flutter_launcher_icons:
  android: true
  ios: false
  image_path: assets/lr.png
  adaptive_icon_background: "#000000"
  adaptive_icon_foreground: assets/lr.png
